# Generated by Django 4.1.4 on 2022-12-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'EMPLOYEES',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=25)),
                ('eID', models.ForeignKey(db_column='eID', on_delete=django.db.models.deletion.CASCADE, to='manageEmployee.employee')),
            ],
            options={
                'db_table': 'PRODUCTS',
            },
        ),
    ]
